<a href="https://colab.research.google.com/github/ff23108ff/20230205-Python/blob/main/20230219.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20230219 筆記

### Q: "%"(取餘數) 怎麼使用?

參考: https://python.microbit.org/v/3

嘗試執行底下程式，按按鈕A觀察結果！

```python

# Imports go at the top
from microbit import *

display.clear()

x = 0
y = 0
display.set_pixel(x,y,9)

while True:
    if button_a.was_pressed():
        x = x + 1
        display.clear()
        display.set_pixel(x%5,y,9)
```

## 複習一下 requests 的使用
 
從政府資料開放平台抓資料：https://data.gov.tw/

### 練習

抓取`年度國內主要金融指標`下來做分析

https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp

In [1]:
import requests

In [2]:
url = "https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp"

In [3]:
data = requests.get(url).json()

In [4]:
# 列出 data 裡面所有的東西
data

[{'年度': '1994',
  '貨幣供給額期底年增率-M1B': '12.23',
  '貨幣供給額期底年增率-M2': '15.07',
  '金價（美元／英兩）-國際現貨黃金價格': '382.50',
  '金價（美元／英兩）-台北': '385.07',
  '匯率（月底）-（新台幣／美元）': '26.240',
  '外匯存底（億美元）': '924.54',
  '利率（年息%）-金融業拆款': '6.130',
  '利率（年息%）-商業本票31-90天期': '6.77',
  '利率（年息%）-中央銀行重貼現率': '5.500',
  '利率（年息%）-債券市場（十年期中央政府公債）': '7.24',
  '證券（集中市場）-發行量加權股價指數（月底）': '7124.66',
  '證券（集中市場）-成交值（億元）': '194766'},
 {'年度': '1995',
  '貨幣供給額期底年增率-M1B': '0.76',
  '貨幣供給額期底年增率-M2': '9.42',
  '金價（美元／英兩）-國際現貨黃金價格': '386.65',
  '金價（美元／英兩）-台北': '388.51',
  '匯率（月底）-（新台幣／美元）': '27.265',
  '外匯存底（億美元）': '903.10',
  '利率（年息%）-金融業拆款': '6.191',
  '利率（年息%）-商業本票31-90天期': '6.68',
  '利率（年息%）-中央銀行重貼現率': '5.500',
  '利率（年息%）-債券市場（十年期中央政府公債）': '6.79',
  '證券（集中市場）-發行量加權股價指數（月底）': '5173.73',
  '證券（集中市場）-成交值（億元）': '103052'},
 {'年度': '1996',
  '貨幣供給額期底年增率-M1B': '8.31',
  '貨幣供給額期底年增率-M2': '9.13',
  '金價（美元／英兩）-國際現貨黃金價格': '369.30',
  '金價（美元／英兩）-台北': '368.08',
  '匯率（月底）-（新台幣／美元）': '27.491',
  '外匯存底（億美元）': '880.38',
  '利率（年息%）-金融業拆款': '5.439',
 

In [7]:
# 檢視data的資料型態
type(data)

list

In [9]:
# 減試一下 data 裡面有幾筆資料
len(data)

29

In [11]:
# 檢視一下 data 的第一筆資料
data[0]

{'年度': '1994',
 '貨幣供給額期底年增率-M1B': '12.23',
 '貨幣供給額期底年增率-M2': '15.07',
 '金價（美元／英兩）-國際現貨黃金價格': '382.50',
 '金價（美元／英兩）-台北': '385.07',
 '匯率（月底）-（新台幣／美元）': '26.240',
 '外匯存底（億美元）': '924.54',
 '利率（年息%）-金融業拆款': '6.130',
 '利率（年息%）-商業本票31-90天期': '6.77',
 '利率（年息%）-中央銀行重貼現率': '5.500',
 '利率（年息%）-債券市場（十年期中央政府公債）': '7.24',
 '證券（集中市場）-發行量加權股價指數（月底）': '7124.66',
 '證券（集中市場）-成交值（億元）': '194766'}

### 列出各年度的M2貨幣供給額


#### 方法1
\

In [12]:
# 利用迴圈列出各年度的M2貨幣供給額
for i in data:
  print(i['年度'], "==>", i['貨幣供給額期底年增率-M2'])

1994 ==> 15.07
1995 ==> 9.42
1996 ==> 9.13
1997 ==> 8.02
1998 ==> 8.56
1999 ==> 8.29
2000 ==> 6.50
2001 ==> 4.31
2002 ==> 2.53
2003 ==> 5.68
2004 ==> 7.19
2005 ==> 6.63
2006 ==> 5.15
2007 ==> 0.84
2008 ==> 7.21
2009 ==> 5.78
2010 ==> 5.44
2011 ==> 4.84
2012 ==> 3.46
2013 ==> 5.79
2014 ==> 6.13
2015 ==> 5.80
2016 ==> 3.55
2017 ==> 3.56
2018 ==> 2.65
2019 ==> 4.52
2020 ==> 9.36
2021 ==> 7.35
2022 ==> 6.74


#### 方法2

In [14]:
for i in range(len(data)):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28


In [21]:
for i in range(len(data)):
 print(data[i]['年度'], "==>", data[i]['貨幣供給額期底年增率-M2'])

1994 ==> 15.07
1995 ==> 9.42
1996 ==> 9.13
1997 ==> 8.02
1998 ==> 8.56
1999 ==> 8.29
2000 ==> 6.50
2001 ==> 4.31
2002 ==> 2.53
2003 ==> 5.68
2004 ==> 7.19
2005 ==> 6.63
2006 ==> 5.15
2007 ==> 0.84
2008 ==> 7.21
2009 ==> 5.78
2010 ==> 5.44
2011 ==> 4.84
2012 ==> 3.46
2013 ==> 5.79
2014 ==> 6.13
2015 ==> 5.80
2016 ==> 3.55
2017 ==> 3.56
2018 ==> 2.65
2019 ==> 4.52
2020 ==> 9.36
2021 ==> 7.35
2022 ==> 6.74


## 資料分析基礎套件

* numpy ==>科學運算基礎套件
* matplotlib ==>繪圖機處套件
* pandas ==>資料分析基礎套件


### 套件載入的慣用法

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```



### numpy

numpy ==> **Num**erical **Py**thon

* ndarray (多維陣列) ==> N-Dimensional Arrays
* ufunc(通用函示) ==>Universal Functions


In [22]:
import numpy as np

### 原生的python的容器型別的限制

無法簡單的做到科學運算(向量運算)!


In [23]:
x = [1, 2, 3]
y = [4, 5, 6]

In [24]:
x + y

[1, 2, 3, 4, 5, 6]

In [25]:
2 * x

[1, 2, 3, 1, 2, 3]

#### 使用numpy的ndarray來解決科學運算的問題

In [26]:
x1 = np.array(x)
y1 = np.array(y)

In [27]:
type(x1)

numpy.ndarray

In [29]:
x1

array([1, 2, 3])

In [30]:
y1

array([4, 5, 6])

In [28]:
x1 + y1

array([5, 7, 9])